name: Python App CI/CD

on:
  push:
    branches: [ main ] # Trigger the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout the repository's code

     - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t alirana05/flask-app:latest .
        working-directory: .

      - name: Push Docker Image
        run: docker push alirana05/flask-app:latest